#define CONFIG
#define FLIGHT true

#define UI_PORT Serial
#define UI_BAUD 115200

#define RF_UPLINK_PORT Serial1
#define RF_UPLINK_BAUD 115200

#define RF_AV_DOWNLINK_PORT Serial2
#define RF_AV_DOWNLINK_BAUD 115200

#define RF_GSE_DOWNLINK_PORT Serial3
#define RF_GSE_DOWNLINK_BAUD 115200

#define COMMAND_INPUT_PORT Serial4
#define COMMAND_INPUT_BAUD 115200

#define NEOPIXEL_A_PIN 33
#define NEOPIXEL_B_PIN 32

#define NOMINAL_AV_RATE 0.2
#define NOMINAL_BINOC_RATE 100

#define POSITION_ESTIMATION_RATE 10